// Mocks generated by Mockito 5.4.4 from annotations
// in accumulate_api/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i6;

import 'package:accumulate_api/src/acme_client.dart' as _i11;
import 'package:accumulate_api/src/client/acc_url.dart' as _i3;
import 'package:accumulate_api/src/client/signer.dart' as _i2;
import 'package:accumulate_api/src/client/tx_signer.dart' as _i5;
import 'package:accumulate_api/src/model/api_types.dart' as _i12;
import 'package:accumulate_api/src/model/tx.dart' as _i14;
import 'package:accumulate_api/src/payload_b.dart' as _i13;
import 'package:accumulate_api/src/transaction.dart' as _i8;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSigner_0 extends _i1.SmartFake implements _i2.Signer {
  _FakeSigner_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccURL_1 extends _i1.SmartFake implements _i3.AccURL {
  _FakeAccURL_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignerInfo_2 extends _i1.SmartFake implements _i2.SignerInfo {
  _FakeSignerInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignature_3 extends _i1.SmartFake implements _i2.Signature {
  _FakeSignature_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TxSigner].
///
/// See the documentation for Mockito's code generation for more information.
class MockTxSigner extends _i1.Mock implements _i5.TxSigner {
  MockTxSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Signer get signer => (super.noSuchMethod(
        Invocation.getter(#signer),
        returnValue: _FakeSigner_0(
          this,
          Invocation.getter(#signer),
        ),
      ) as _i2.Signer);

  @override
  _i3.AccURL get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _FakeAccURL_1(
          this,
          Invocation.getter(#url),
        ),
      ) as _i3.AccURL);

  @override
  set url(_i3.AccURL? value) => super.noSuchMethod(
        Invocation.setter(
          #url,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Uint8List get publicKey => (super.noSuchMethod(
        Invocation.getter(#publicKey),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  _i6.Uint8List get secretKey => (super.noSuchMethod(
        Invocation.getter(#secretKey),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  String get mnemonic => (super.noSuchMethod(
        Invocation.getter(#mnemonic),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#mnemonic),
        ),
      ) as String);

  @override
  _i6.Uint8List get publicKeyHash => (super.noSuchMethod(
        Invocation.getter(#publicKeyHash),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);

  @override
  _i2.SignerInfo get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: _FakeSignerInfo_2(
          this,
          Invocation.getter(#info),
        ),
      ) as _i2.SignerInfo);

  @override
  _i2.Signature sign(_i8.Transaction? tx) => (super.noSuchMethod(
        Invocation.method(
          #sign,
          [tx],
        ),
        returnValue: _FakeSignature_3(
          this,
          Invocation.method(
            #sign,
            [tx],
          ),
        ),
      ) as _i2.Signature);
}

/// A class which mocks [Signer].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigner extends _i1.Mock implements _i2.Signer {
  MockSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set type(int? _type) => super.noSuchMethod(
        Invocation.setter(
          #type,
          _type,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Uint8List signRaw(_i6.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #signRaw,
          [data],
        ),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  _i6.Uint8List publicKey() => (super.noSuchMethod(
        Invocation.method(
          #publicKey,
          [],
        ),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  _i6.Uint8List secretKey() => (super.noSuchMethod(
        Invocation.method(
          #secretKey,
          [],
        ),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  _i6.Uint8List publicKeyHash() => (super.noSuchMethod(
        Invocation.method(
          #publicKeyHash,
          [],
        ),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  String mnemonic() => (super.noSuchMethod(
        Invocation.method(
          #mnemonic,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #mnemonic,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i4.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i4.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i6.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i9.Future<_i6.Uint8List>);

  @override
  _i9.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_5(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ACMEClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockACMEClient extends _i1.Mock implements _i11.ACMEClient {
  MockACMEClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<Map<String, dynamic>> call(
    String? method, [
    Map<String, dynamic>? params,
    bool? supressLog,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            method,
            params,
            supressLog,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> execute(
    _i8.Transaction? tx, {
    bool? suppressLog = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tx],
          {#suppressLog: suppressLog},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> executeDirect() => (super.noSuchMethod(
        Invocation.method(
          #executeDirect,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryAcmeOracle() => (super.noSuchMethod(
        Invocation.method(
          #queryAcmeOracle,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryData(
    dynamic url, [
    String? entryHash,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryData,
          [
            url,
            entryHash,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryAnchor(String? anchor) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAnchor,
          [anchor],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryUrl(
    dynamic url, [
    _i12.QueryOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryUrl,
          [
            url,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryTx(
    String? txRef, [
    _i12.TxQueryOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryTx,
          [
            txRef,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryTxByUrl(
    String? txId, [
    _i12.TxQueryOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryTxByUrl,
          [
            txId,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryTxHistory(
    dynamic url,
    _i12.QueryPagination? pagination,
    _i12.TxHistoryQueryOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryTxHistory,
          [
            url,
            pagination,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryDataSet(
    dynamic url,
    _i12.QueryPagination? pagination,
    _i12.QueryOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryDataSet,
          [
            url,
            pagination,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryKeyPageIndex(
    dynamic url,
    dynamic key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryKeyPageIndex,
          [
            url,
            key,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryMinorBlocks(
    String? url,
    _i12.QueryPaginationForBlocks? pagination,
    _i12.MinorBlocksQueryOptions? options, [
    bool? supressLog,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMinorBlocks,
          [
            url,
            pagination,
            options,
            supressLog,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> queryMajorBlocks(
    String? url,
    _i12.QueryPaginationForBlocks? pagination,
    _i12.MinorBlocksQueryOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMajorBlocks,
          [
            url,
            pagination,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<int> querySignerVersion(
    dynamic signer,
    _i6.Uint8List? publicKeyHash,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #querySignerVersion,
          [
            signer,
            publicKeyHash,
          ],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Map<String, dynamic>> queryDirectory(
    dynamic url,
    _i12.QueryPagination? pagination,
    _i12.QueryOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryDirectory,
          [
            url,
            pagination,
            options,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  dynamic waitOnTx(
    int? startTime,
    String? txId, [
    _i12.WaitTxOptions? options,
  ]) =>
      super.noSuchMethod(Invocation.method(
        #waitOnTx,
        [
          startTime,
          txId,
          options,
        ],
      ));

  @override
  _i9.Future<Map<String, dynamic>> addCredits(
    dynamic principal,
    _i13.AddCreditsParam? addCredits,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCredits,
          [
            principal,
            addCredits,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> addValidator(
    dynamic principal,
    _i13.AddValidatorParam? addValidator,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addValidator,
          [
            principal,
            addValidator,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> burnTokens(
    dynamic principal,
    _i13.BurnTokensParam? burnTokens,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #burnTokens,
          [
            principal,
            burnTokens,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createDataAccount(
    dynamic principal,
    _i13.CreateDataAccountParam? createDataAccount,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDataAccount,
          [
            principal,
            createDataAccount,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createIdentity(
    dynamic principal,
    _i13.CreateIdentityParam? createIdentity,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIdentity,
          [
            principal,
            createIdentity,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createKeyBook(
    dynamic principal,
    _i13.CreateKeyBookParam? createKeyBook,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKeyBook,
          [
            principal,
            createKeyBook,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createKeyPage(
    dynamic principal,
    _i13.CreateKeyPageParam? createKeyPage,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKeyPage,
          [
            principal,
            createKeyPage,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createToken(
    dynamic principal,
    _i13.CreateTokenParam? createToken,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [
            principal,
            createToken,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createTokenAccount(
    dynamic principal,
    _i13.CreateTokenAccountParam? createTokenAccount,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTokenAccount,
          [
            principal,
            createTokenAccount,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> issueTokens(
    dynamic principal,
    _i13.IssueTokensParam? issueTokens,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #issueTokens,
          [
            principal,
            issueTokens,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> removeValidator(
    dynamic principal,
    _i13.RemoveValidatorArg? removeValidator,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeValidator,
          [
            principal,
            removeValidator,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> sendTokens(
    dynamic principal,
    _i13.SendTokensParam? sendTokens,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTokens,
          [
            principal,
            sendTokens,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> updateAccountAuth(
    dynamic principal,
    _i13.UpdateAccountAuthParam? updateAccountAuthParam,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccountAuth,
          [
            principal,
            updateAccountAuthParam,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> updateKey(
    dynamic principal,
    _i13.UpdateKeyParam? updateKey,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKey,
          [
            principal,
            updateKey,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> updateKeyPage(
    dynamic principal,
    _i13.UpdateKeyPageParam? updateKeyPageParam,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKeyPage,
          [
            principal,
            updateKeyPageParam,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> updateValidatorKey(
    dynamic principal,
    _i13.UpdateValidatorKeyParam? updateValidatorKey,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateValidatorKey,
          [
            principal,
            updateValidatorKey,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> writeData(
    dynamic principal,
    _i13.WriteDataParam? writeData,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeData,
          [
            principal,
            writeData,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> faucet(_i3.AccURL? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #faucet,
          [url],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> faucetSimple(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #faucetSimple,
          [url],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> status() => (super.noSuchMethod(
        Invocation.method(
          #status,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> version() => (super.noSuchMethod(
        Invocation.method(
          #version,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> describe() => (super.noSuchMethod(
        Invocation.method(
          #describe,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> metrics(
    String? metric,
    int? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #metrics,
          [
            metric,
            duration,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<int> valueFromOracle() => (super.noSuchMethod(
        Invocation.method(
          #valueFromOracle,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<List<int>> getAdiSlidingFee() => (super.noSuchMethod(
        Invocation.method(
          #getAdiSlidingFee,
          [],
        ),
        returnValue: _i9.Future<List<int>>.value(<int>[]),
      ) as _i9.Future<List<int>>);

  @override
  _i9.Future<_i14.Transaction?> callGetTokenTransaction(
    String? txhash, [
    String? addr,
    bool? isLookupByUrl,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #callGetTokenTransaction,
          [
            txhash,
            addr,
            isLookupByUrl,
          ],
        ),
        returnValue: _i9.Future<_i14.Transaction?>.value(),
      ) as _i9.Future<_i14.Transaction?>);

  @override
  _i9.Future<List<_i14.Transaction>> callGetTokenTransactionHistory(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #callGetTokenTransactionHistory,
          [path],
        ),
        returnValue:
            _i9.Future<List<_i14.Transaction>>.value(<_i14.Transaction>[]),
      ) as _i9.Future<List<_i14.Transaction>>);

  @override
  _i9.Future<Map<String, dynamic>> factom(
    dynamic principal,
    _i13.FactomDataEntryParam? factomParam,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #factom,
          [
            principal,
            factomParam,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createLiteDataAccount(
    dynamic principal,
    _i13.CreateLiteDataAccountParam? createLiteDataAccountParam,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLiteDataAccount,
          [
            principal,
            createLiteDataAccountParam,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> writeDataTo(
    dynamic principal,
    _i13.WriteDataToParam? writeDataToParam,
    _i5.TxSigner? signer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeDataTo,
          [
            principal,
            writeDataToParam,
            signer,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);
}
